In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv


In [2]:
data = pd.read_csv("/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv")

In [3]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
data.shape

(10000, 14)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
data["Exited"].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [8]:
data["Gender"].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [9]:
data["Tenure"].value_counts()

2     1048
1     1035
7     1028
8     1025
5     1012
3     1009
4      989
9      984
6      967
10     490
0      413
Name: Tenure, dtype: int64

In [10]:
data["IsActiveMember"].value_counts()

1    5151
0    4849
Name: IsActiveMember, dtype: int64

In [11]:
data["HasCrCard"].value_counts()

1    7055
0    2945
Name: HasCrCard, dtype: int64

In [12]:
data["NumOfProducts"].value_counts()

1    5084
2    4590
3     266
4      60
Name: NumOfProducts, dtype: int64

In [13]:
data["Gender"].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [14]:
data["Geography"].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [16]:
data = data.drop(columns=["RowNumber","CustomerId","Surname"])

In [17]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [18]:
data = pd.get_dummies(data,columns=["Geography","Gender"],drop_first=True)

In [19]:
data

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1                  0   
1                  1        112542.58       0                  0   
2                  0        113931.57       1                  0   
3                  0         93826.63       0                  0   
4                  1         79084.10       0                  0   
...              ...              ...     ...                ...   
9995               0         96270.64       0                  0   
9996               1        101699.77       0                  0   
9997               1         42085.58       1                  0   
9998               0         92888.52       1                  1   
9999               0         38190.78       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [20]:
x = data.drop(columns=["Exited"])
y = data["Exited"]

In [21]:
x

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0                  1        101348.88                  0                0   
1                  1        112542.58                  0                1   
2                  0        113931.57                  0                0   
3                  0         93826.63                  0                0   
4                  1         79084.10                  0                1   
...              ...              ...                ...              ...   
9995               0         96270.64                  0                0   
9996               1        101699.77                  0                0   
9997               1         42085.58                  0                0   
9998               0         92888.52                  1                0   
9999               0         38190.78                  0                0   

      Gender_Male  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
9995            1  
9996            1  
9997            0  
9998            1  
9999            0  

[10000 rows x 11 columns]

In [22]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [26]:
x_train

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
4384          728   37       0       0.00              2          1   
3834          734   39       6   92126.26              2          0   
9032          781   27       5       0.00              2          0   
6138          477   47       9  144900.58              1          1   
1532          661   32       1  145980.23              1          0   
...           ...  ...     ...        ...            ...        ...   
2922          685   34       6   83264.28              1          0   
4354          558   45       4       0.00              1          1   
3793          727   58       5  106913.43              1          1   
9943          784   23       2       0.00              1          1   
8248          633   29       6  117412.35              1          0   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
4384               1         72203.80                  0                0   
3834               0        112973.34                  0                1   
9032               0         72969.90                  0                0   
6138               0         61315.37                  0                0   
1532               1         56636.28                  1                0   
...              ...              ...                ...              ...   
2922               0          9663.28                  0                1   
4354               0        131807.14                  0                1   
3793               0         25881.00                  1                0   
9943               1          6847.73                  0                1   
8248               0         30338.94                  1                0   

      Gender_Male  
4384            1  
3834            0  
9032            0  
6138            1  
1532            0  
...           ...  
2922            1  
4354            1  
3793            1  
9943            1  
8248            1  

[8000 rows x 11 columns]

In [27]:
y_train

4384    0
3834    0
9032    0
6138    1
1532    0
       ..
2922    0
4354    0
3793    1
9943    0
8248    0
Name: Exited, Length: 8000, dtype: int64

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [30]:
x_test_scaled

array([[-0.08021755,  0.19967   , -0.35735582, ...,  1.73668197,
        -0.57504086,  0.90750738],
       [ 0.71416881,  0.96272486, -0.01028206, ..., -0.57581067,
        -0.57504086,  0.90750738],
       [-0.6785865 , -0.27723929,  1.37801299, ..., -0.57581067,
        -0.57504086,  0.90750738],
       ...,
       [-1.1944218 , -0.56338487, -0.70442958, ..., -0.57581067,
         1.73900686, -1.10191942],
       [ 0.87923611,  0.39043371,  1.72508675, ...,  1.73668197,
        -0.57504086,  0.90750738],
       [ 0.20865022,  0.39043371, -1.39857711, ..., -0.57581067,
         1.73900686,  0.90750738]])

In [31]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [57]:
model = Sequential()
model.add(Dense(4,activation="relu",input_dim = 11))
model.add(Dense(4,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [58]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 4)                 48        
_________________________________________________________________
dense_7 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 5         
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


In [59]:
model.compile(loss="binary_crossentropy",optimizer="Adam")

In [60]:
model.fit(x_train_scaled,y_train,epochs=200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.5784
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4932
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4614
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4483
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4417
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4375
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4332
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4285
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4246
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4210
Epoch 11/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4177
Epoch 12/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4152
Epoch 13/200


In [61]:
model.layers[0].get_weights()

[array([[-0.02599196,  0.0782994 , -0.01566083,  0.10723385],
        [-0.5360995 , -0.0573303 ,  0.10380208, -1.0197135 ],
        [ 0.03476153, -0.05481167,  0.02351748, -0.00877618],
        [ 0.06359611, -0.4641102 , -0.21569423, -0.00797179],
        [-1.4027567 , -1.2174742 , -0.5791597 , -0.3620005 ],
        [ 0.02430099, -0.00946127,  0.01637037, -0.0337581 ],
        [ 0.373581  , -0.54600185,  0.30376002, -0.3721462 ],
        [ 0.04239275,  0.01753044, -0.00839259,  0.0522799 ],
        [-0.05887424,  0.2428734 ,  0.02155829, -0.01050859],
        [-0.09713329,  0.04979564, -0.02304517, -0.00912719],
        [ 0.06675158,  0.02009759,  0.10570598,  0.02110558]],
       dtype=float32),
 array([ 0.4974481 , -0.16061799,  1.8396341 ,  1.3390402 ], dtype=float32)]

In [62]:
model.layers[1].get_weights()

[array([[-0.09907434,  0.5744332 , -0.19438706, -0.6562554 ],
        [-0.4621395 ,  0.8159999 ,  0.10460658, -1.4302931 ],
        [ 1.56918   , -0.36612096,  0.45310324,  0.7837913 ],
        [ 0.56299067, -0.970994  ,  0.1476039 ,  0.36285788]],
       dtype=float32),
 array([-0.19454022,  1.1160057 , -0.13166435, -0.45713362], dtype=float32)]

In [63]:
y_log = model.predict(x_test_scaled)
y_log

array([[0.3877656 ],
       [0.16221473],
       [0.15024003],
       ...,
       [0.18012351],
       [0.04517874],
       [0.3151843 ]], dtype=float32)

In [64]:
y_pred = np.where(y_log>0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.869